version: "3.4"
services:

  mongo001:
    hostname: mongo001
    container_name: mongo001
    image: mongo:4.0
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    command: mongod --bind_ip_all --auth
    volumes:
      - ./data/mongo001:/data/db
      - ./config/mongodb/mongo001.js:/docker-entrypoint-initdb.d/config.js
