spring:
  data:
    mongodb:
      host: ds141188.mlab.com
      port: 41188
      username: rolandonanet
      password: MOV@43214244884
      authentication-database: presencelist
      database: presencelist
  server:
    port: 8080
    servlet:
      context-path: /presence_list/api
