spring:
  data:
    mongodb:
      host: ds141188.mlab.com:41188/heroku_2h0prhnv
      username: rolandonanet  
      password: MOV@43214244884
      authentication-database: presencelist
      database: presencelist
  server:
    port: 8080
    servlet:
      context-path: /presence_list/api
