spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: 
      password: 
      authentication-database: presencelist
      database: presencelist
  server:
    port: 8080
    servlet:
      context-path: /presence_list/api